TARGET = main

# repertoire des modules
#AVERSIVE_DIR = ../../../libs/aversive_b_zer0_9oct09
AVERSIVE_DIR = ../../../libs/aversive4dspic

SRC  = $(TARGET).c

ASRC = 

#CFLAGS += -Wall -Werror

########################################

-include .aversive_conf
include $(AVERSIVE_DIR)/mk/aversive_project.mk

